export const TAG_POOL = [
  "bug",
  "feature",
  "docs",
  "refactor",
  "test",
  "ux",
  "perf",
  "security",
];

export const TASK_TITLES = [
  "Implement user authentication flow",
  "Fix pagination bug on dashboard",
  "Refactor API response caching",
  "Add unit tests for payment module",
  "Design new onboarding screens",
  "Migrate database to PostgreSQL",
  "Set up CI/CD pipeline",
  "Resolve memory leak in worker service",
  "Update API documentation",
  "Implement dark mode support",
  "Add CSV export feature",
  "Fix broken layout on mobile",
  "Code review for PR #241",
  "Performance audit on search endpoint",
  "Write E2E tests for checkout flow",
  "Integrate third-party analytics SDK",
  "Sync translations for 5 locales",
  "Harden input validation across forms",
  "Investigate flaky test in CI",
  "Deploy hotfix to staging",
];
